#!/usr/bin/env bash
# Build a clean-room sandbox for evaluating the zul-writer skill.
#
# Why this exists: testing the skill inside this repository measures recall, not
# generation. Every mockup in zulwriter-showcase/ui-screenshots/ already has its
# committed .zul and controller a few directories away, and the six-run
# evaluation concluded on that basis that its remaining material was used up.
# That conclusion depends on the generation happening *here*. It does not have to.
#
# What the sandbox is: a Maven webapp outside this repository containing the
# project plumbing, one mockup, and a copy of the skill -- and nothing else. No
# .zul, no controller, no other screenshot, no RULES.md, no README, no target/,
# no CLAUDE.md. The isolation is structural rather than an instruction the
# examinee is asked to honour.
#
#   ./test/cleanroom/make-sandbox.sh "Data Analytics Dashboard" pilot-01
#
# Two things this script CANNOT do, both stated in the generated MANIFEST.md:
#   * The globally installed skill is a symlink into this repository, so an agent
#     that resolves it can walk back to the showcase. The sandbox ships its own
#     copy under .claude/skills/; the global symlink is the residual leak.
#   * Isolation is about context, not disk. Whoever ran a session that has
#     already read this repository's file listing cannot then be the examinee.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SHOWCASE="$REPO/zulwriter-showcase"
MOCKUP_NAME="${1:?usage: make-sandbox.sh <mockup name without .png> [sandbox-name]}"
SANDBOX_NAME="${2:-pilot-01}"
ROOT="$HOME/Documents/workspace/zul-writer-cleanroom/$SANDBOX_NAME"

MOCKUP="$SHOWCASE/ui-screenshots/$MOCKUP_NAME.png"
[ -f "$MOCKUP" ] || { echo "no such mockup: $MOCKUP" >&2; exit 1; }
[ -e "$ROOT" ] && { echo "refusing to overwrite existing sandbox: $ROOT" >&2; exit 1; }

mkdir -p "$ROOT"/src/main/webapp/WEB-INF \
         "$ROOT"/src/main/java/zwriter \
         "$ROOT"/.claude/skills \
         "$ROOT"/mockup \
         "$ROOT"/out

# Plumbing, copied verbatim on purpose. zk.xml is copied unedited even though it
# forwards every Throwable to a /error.zul that does not exist -- that quirk was
# present when the baseline render counts were measured, so importing it keeps
# the comparison honest. Fixing it here would make the pilot faster for a reason
# that has nothing to do with the skill.
cp "$SHOWCASE/pom.xml"                        "$ROOT/pom.xml"
cp "$SHOWCASE/src/main/webapp/WEB-INF/web.xml" "$ROOT/src/main/webapp/WEB-INF/web.xml"
cp "$SHOWCASE/src/main/webapp/WEB-INF/zk.xml"  "$ROOT/src/main/webapp/WEB-INF/zk.xml"

# A copy, never a symlink: a symlink is a path back to the answers.
cp -R "$REPO/skills/zul-writer" "$ROOT/.claude/skills/zul-writer"
find "$ROOT/.claude/skills/zul-writer" -name '.DS_Store' -delete 2>/dev/null || true

cp "$MOCKUP" "$ROOT/mockup/$MOCKUP_NAME.png"

cat > "$ROOT/MANIFEST.md" <<EOF
# What is in this sandbox, and what was kept out

Generated by \`test/cleanroom/make-sandbox.sh\` from the agent-skill repository.

## Present
- \`pom.xml\`, \`WEB-INF/web.xml\`, \`WEB-INF/zk.xml\` — copied verbatim from the showcase
- \`.claude/skills/zul-writer/\` — a **copy** of the skill under test
- \`mockup/$MOCKUP_NAME.png\` — the single input
- empty \`src/main/webapp/\` and \`src/main/java/zwriter/\`

## Deliberately absent
- every other mockup, and every generated \`.zul\` and controller
- \`RULES.md\` (its CSS-class rule duplicates one of the skill's own guidelines)
- \`README.md\` (a prompt-to-output table: the assignment sheet)
- \`target/\` (compiled composers, which the preview puts on its classpath)
- this repository's \`CLAUDE.md\`

## Residual leaks, stated rather than hidden
1. **The global skill install is a symlink** into the agent-skill repository.
   Resolving it and walking up two levels reaches the showcase. Nothing instructs
   an agent to do that, but it is possible. To close it for the duration:
   \`mv ~/.claude/skills/zul-writer ~/.claude/skills/zul-writer.off\` and restore afterwards.
2. **Isolation is about context, not disk.** A session that has already read the
   agent-skill file listing cannot be the examinee, whichever directory it runs in.
3. The launcher jar cache (\`~/.cache/zul-writer\`) is shared. It holds binaries and
   resolved classpaths, no page content.
EOF

cat > "$ROOT/BRIEF.md" <<EOF
Build a ZK page from this design mockup:
\`$ROOT/mockup/$MOCKUP_NAME.png\`

Use the \`zul-writer\` skill.

Requirements already settled — do not re-ask these:

* ZK version: **10.x**
* Pattern: **MVVM**, i.e. a ViewModel
* Data: **model-driven** — the ViewModel supplies the values and the rows, not the ZUL

## Where things go

* Project root: \`$ROOT\`
* Put the \`.zul\` in \`src/main/webapp/\`. You choose the filename.
* Put the Java ViewModel in \`src/main/java/zwriter/\`, package \`zwriter\`.
* The project builds with \`mvn\` (offline-capable — use \`-o\` if it hangs on the network).

## Preview

* Run the preview script with \`uv run\`, e.g.
  \`uv run .claude/skills/zul-writer/scripts/preview-zul.py <flags> <file.zul>\`
* The launcher jar is pinned and will be fetched or taken from cache. No extra flag needed.
* Write preview PNGs under \`$ROOT/out/\`.

## What to leave behind

Write \`$ROOT/out/RUNLOG.md\` as you go — not at the end from memory. It must record:

1. Which steps of the skill you ran, in order, and any you skipped with why.
2. Every command you ran, with its exact flags, and its exit status.
3. **How many times you rendered a preview, and what you changed between one render
   and the next.** This is the measurement; be exact.
4. Whether you looked anything up before writing it, and with what command.
5. Every point where you were unsure what the instructions meant, or had to work
   around a tool. Be blunt — this is the part that matters.

Finish by reporting the absolute path of the final \`.zul\`, the final \`.java\`, and
the final preview PNG.
EOF

echo "sandbox ready: $ROOT"
echo
echo "contents:"
find "$ROOT" -maxdepth 2 -not -path '*/.claude/skills/zul-writer/*' | sed "s|$ROOT|.|" | sort
echo
echo "skill copy: $(find "$ROOT/.claude/skills/zul-writer" -type f | wc -l | tr -d ' ') files"
echo "leaked .zul or controllers in sandbox: $(find "$ROOT/src" -name '*.zul' -o -name '*.java' | wc -l | tr -d ' ') (must be 0)"
